FORMAT: 1A
HOST: http://www.bestbytes.me

# BestBytes

Bestbytes API is a simple API that gives a variety of articles, their sources and locations.

## All Data Collection [/api/all]

### Get All Data [GET]

+ Response 200 (application/json)

        {
            "articles": [
                {
                    "category": "string",
                    "description": "string",
                    "external_article_link": "string",
                    "external_source_link": "string",
                    "id_num": "string",
                    "image_link": "string",
                    "pubDate": "string",
                    "region": "string",
                    "source_name": "string",
                    "title": "string"
                }
            ],
            "sources": [
                {
                    "category": "string",
                    "country": "string",
                    "description": "string",
                    "external_link": "string",
                    "id_name": "string",
                    "id_num": "string",
                    "language": "string",
                    "largeLogoURL": "string",
                    "mediumLogoURL": "string",
                    "name": "string",
                    "region": "string",
                    "smallLogoURL": "string"
                }
            ],
            "locations": [
                {
                    "capital": "string",
                    "currencies": "string",
                    "id_num": "string",
                    "languages": "string",
                    "latlng": "string",
                    "name": "string",
                    "population": "string",
                    "region":, "string",
                    "topLevelDomain": "string"
                }
            ]
        }

## Articles Collection [/api/articles/all]

### Get All Articles [GET]

+ Response 200 (application/json)

        {
            "articles": [
                {
                    "category": "string",
                    "description": "string",
                    "external_article_link": "string",
                    "external_source_link": "string",
                    "id_num": "string",
                    "image_link": "string",
                    "pubDate": "string",
                    "region": "string",
                    "source_name": "string",
                    "title": "string"
                }
            ]
        }

## Articles by Page [/api/articles/page={page_num}]

+ Parameters
    + page_num (number) - Page number in the form of an integer

### Get 50 Articles  [GET]

+ Response 200 (application/json)

        {
            "articles": [
                {
                    "category": "string",
                    "description": "string",
                    "external_article_link": "string",
                    "external_source_link": "string",
                    "id_num": "string",
                    "image_link": "string",
                    "pubDate": "string",
                    "region": "string",
                    "source_name": "string",
                    "title": "string"
                }
            ]
        }

## Article by ID [/api/articles/id={id_num}]

+ Parameters
    + id_num (number) - Article identification number in the form of an integer

### Get Specific Article  [GET]

+ Response 200 (application/json)

        {
            "category": "string",
            "description": "string",
            "external_article_link": "string",
            "external_source_link": "string",
            "id_num": "string",
            "image_link": "string",
            "pubDate": "string",
            "region": "string",
            "source_name": "string",
            "title": "string"
        }

## Source Collection [/api/sources/all]

### Get All Sources [GET]

+ Response 200 (application/json)

        {
            "sources": [
                    {
                        "category": "string",
                        "country": "string",
                        "description": "string",
                        "external_link": "string",
                        "id_name": "string",
                        "id_num": "string",
                        "language": "string",
                        "largeLogoURL": "string",
                        "mediumLogoURL": "string",
                        "name": "string",
                        "region": "string",
                        "smallLogoURL": "string"
                    }
            ]
        }
        
## Sources by Page [/api/sources/page={page_num}]

+ Parameters
    + page_num (number) - Page number in the form of an integer

### Get 25 Sources [GET]

+ Response 200 (application/json)

        {
            "sources": [
                    {
                        "category": "string",
                        "country": "string",
                        "description": "string",
                        "external_link": "string",
                        "id_name": "string",
                        "id_num": "string",
                        "language": "string",
                        "largeLogoURL": "string",
                        "mediumLogoURL": "string",
                        "name": "string",
                        "region": "string",
                        "smallLogoURL": "string"
                    }
            ]
        }
        
## Source by ID [/api/sources/id={id_num}]

+ Parameters
    + id_num (number) - Source identification number in the form of an integer

### Get Specific Source [GET]

+ Response 200 (application/json)

        {
            "category": "string",
            "country": "string",
            "description": "string",
            "external_link": "string",
            "id_name": "string",
            "id_num": "string",
            "language": "string",
            "largeLogoURL": "string",
            "mediumLogoURL": "string",
            "name": "string",
            "region": "string",
            "smallLogoURL": "string"
        }

## Locations Collection [/api/locations/all]

### Get All Locations [GET]

+ Response 200 (application/json)

        {
            "locations": [
                {
                    "capital": "string",
                    "currencies": "string",
                    "id_num": "string",
                    "languages": "string",
                    "latlng": "string",
                    "name": "string",
                    "population": "string",
                    "region":, "string",
                    "topLevelDomain": "string"
                }
            ]
        }
        
## Locations by Page [/api/locations/page={page_num}]

+ Parameters
    + page_num (number) - Page number in the form of an integer

### Get 25 Locations [GET]

+ Response 200 (application/json)

        {
            "locations": [
                {
                    "capital": "string",
                    "currencies": "string",
                    "id_num": "string",
                    "languages": "string",
                    "latlng": "string",
                    "name": "string",
                    "population": "string",
                    "region":, "string",
                    "topLevelDomain": "string"
                }
            ]
        }
        
## Location by ID [/api/locations/id={id_num}]

+ Parameters
    + id_num (number) - Location identification number in the form of an integer
    
### Get Specific Location [GET]

+ Response 200 (application/json)

                {
                    "capital": "string",
                    "currencies": "string",
                    "id_num": "string",
                    "languages": "string",
                    "latlng": "string",
                    "name": "string",
                    "population": "string",
                    "region":, "string",
                    "topLevelDomain": "string"
                }