FORMAT: 1A
HOST: http://www.bestbytes.me

# BestBytes

Bestbytes API is a simple API that gives a variety of articles, their sources and locations.

## All Data Collection [/api/all]

### List All Data

+ Response 200 (json)

    {
        "articles": [
            {
                "category": "string",
                "description": "string",
                "external_article_link": "string",
                "external_source_link": "string",
                "id_num": "string",
                "image_link": "string",
                "pubDate": "string",
                "region": "string",
                "source_name": "string",
                "title": "string"
            }
        ],
        "sources": [
            {
                "category": "string",
                "country": "string",
                "description": "string",
                "external_link": "string",
                "id_name": "string",
                "id_num": "string",
                "language": "string",
                "largeLogoURL": "string",
                "mediumLogoURL": "string",
                "name": "string",
                "region": "string",
                "smallLogoURL": "string"
            }
        ],
        "locations": [
            {
                "capital": "string",
                "currencies": "string",
                "id_num": "string",
                "languages": "string",
                "latlng": "string",
                "name": "string",
                "population": "string",
                "region":, "string",
                "topLevelDomain": "string"
            }
        ]
    }

## Article Collection [/api/articles/all]

### List All Articles [GET]

+ Response 200 (json)

        [
            {
                "title": "Ben Needham 'killed in accident'",
                "excerpt": "Toddler Ben Needham died as a result of an accident near where he was last seen on the Greek island of Kos in 1991, police believe.",
                "source": "BBC News",
                "published at": "2016-10-17T12:35:12Z"
                "author": "BBC News"
            },
            {
                "title": "Ben Needham 'killed in accident'",
                "excerpt": "Toddler Ben Needham died as a result of an accident near where he was last seen on the Greek island of Kos in 1991, police believe.",
                "source": "BBC News",
                "published at": "2016-10-17T12:35:12Z"
                "author": "BBC News"
            },
            {
                "title": "Ben Needham 'killed in accident'",
                "excerpt": "Toddler Ben Needham died as a result of an accident near where he was last seen on the Greek island of Kos in 1991, police believe.",
                "source": "BBC News",
                "published at": "2016-10-17T12:35:12Z"
                "author": "BBC News"
            }
            
        ]

## Article [/articles/{article_id}]

+ Parameters
    + article_id (number) - ID of the Article in the form of an integer

### View an Article detail [GET]

+ Response 200 (application/json)

            {
                "title": "Ben Needham 'killed in accident'",
                "excerpt": "Toddler Ben Needham died as a result of an accident near where he was last seen on the Greek island of Kos in 1991, police believe.",
                "source": "BBC News",
                "published at": "2016-10-17T12:35:12Z"
                "author": "BBC News"
            }


## Source Collection [/sources]

### List All Sources [GET]

+ Response 200 (application/json)

        [
            {
                "name": "BBC News",
                "logo": "http://i.newsapi.org/bbc-news-s.png",
                "country": "Great Britain",
                "language": "English"
                "description": "Use BBC News for up-to-the-minute news, breaking news, video, audio and feature stories. BBC News provides trusted World and UK news as well as local and regional perspectives. Also entertainment, business, science, technology and health news."
            },
            {
                "name": "BBC News",
                "logo": "http://i.newsapi.org/bbc-news-s.png",
                "country": "Great Britain",
                "language": "English"
                "description": "Use BBC News for up-to-the-minute news, breaking news, video, audio and feature stories. BBC News provides trusted World and UK news as well as local and regional perspectives. Also entertainment, business, science, technology and health news."
            },
            {
                "name": "BBC News",
                "logo": "http://i.newsapi.org/bbc-news-s.png",
                "country": "Great Britain",
                "language": "English"
                "description": "Use BBC News for up-to-the-minute news, breaking news, video, audio and feature stories. BBC News provides trusted World and UK news as well as local and regional perspectives. Also entertainment, business, science, technology and health news."
            }
        ]
        
## Source [/sources/{source_id}]

+ Parameters
    + source_id (number) - ID of the Source in the form of an integer

### View a Source Detail [GET]

+ Response 200 (application/json)

        [
            {
                "name": "BBC News",
                "logo": "http://i.newsapi.org/bbc-news-s.png",
                "country": "Great Britain",
                "language": "English"
                "description": "Use BBC News for up-to-the-minute news, breaking news, video, audio and feature stories. BBC News provides trusted World and UK news as well as local and regional perspectives. Also entertainment, business, science, technology and health news."
            }
        ]

## Location Collection [/locations]

### List All Locations [GET/locations]

+ Response 200 (application/json)

        [
            {
                "country": "Europe",
                "logo": "GBP",
                "lat/long": "54,-2",
                "capital": "London"
                "description": "64800000"
            },
            {
                "country": "Europe",
                "logo": "GBP",
                "lat/long": "54,-2",
                "capital": "London"
                "description": "64800000"
            },
            {
                "country": "Europe",
                "logo": "GBP",
                "lat/long": "54,-2",
                "capital": "London"
                "description": "64800000"
            }
        ]
        
## Location [/locations/{location_id}]

+ Parameters
    + location_id (number) - ID of the Location in the form of an integer

### View a Location Detail [GET]

+ Response 200 (application/json)

        [
            {
                "country": "Europe",
                "logo": "GBP",
                "lat/long": "54,-2",
                "capital": "London"
                "description": "64800000"
            }
        ]